Project
kmlcn05/Smurfs1 pull request #12
Opened 2022-06-15 11:54 UTC by kmlcn05

backend yapıldı

2022-06-15 13:57 UTC, muhammetulas commented on Smurfs.Business/Concrete/ProjectManager.cs
> +            if (recordedProject != null)
Burada null ise yeni kayıt eklenmeli. Mevcut kayıt ezilmemeli.

2022-06-15 13:58 UTC, muhammetulas commented on Smurfs.DataAccess/Models/ProjectModel.cs
> +﻿using System;
Bu class gereksiz silinmesi lazım.

2022-06-15 13:58 UTC, muhammetulas requested changes
Yorum ekledim düzeltir misiniz?

2022-06-18 13:15 UTC, murataygn approved these changes

2022-06-18 13:20 UTC, murataygn approved these changes

2022-06-18 16:47 UTC, muhammetulas approved these changes
ok

2022-06-18 16:47 UTC, merged